apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: go-webapp
        image: arsh1/go-app-ms:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80